USE [master]
GO

/****** Object:  Database [Ivanova_AS41_course]    Script Date: 01.12.2022 10:35:58 ******/
CREATE DATABASE [Ivanova_AS41_course]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Ivanova_AS41_course', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Ivanova_AS41_course.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Ivanova_AS41_course_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Ivanova_AS41_course_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Ivanova_AS41_course].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Ivanova_AS41_course] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Ivanova_AS41_course] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Ivanova_AS41_course] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Ivanova_AS41_course] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Ivanova_AS41_course] SET ARITHABORT OFF 
GO

ALTER DATABASE [Ivanova_AS41_course] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Ivanova_AS41_course] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Ivanova_AS41_course] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Ivanova_AS41_course] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Ivanova_AS41_course] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Ivanova_AS41_course] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Ivanova_AS41_course] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Ivanova_AS41_course] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Ivanova_AS41_course] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Ivanova_AS41_course] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Ivanova_AS41_course] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Ivanova_AS41_course] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Ivanova_AS41_course] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Ivanova_AS41_course] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Ivanova_AS41_course] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Ivanova_AS41_course] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Ivanova_AS41_course] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Ivanova_AS41_course] SET RECOVERY FULL 
GO

ALTER DATABASE [Ivanova_AS41_course] SET  MULTI_USER 
GO

ALTER DATABASE [Ivanova_AS41_course] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Ivanova_AS41_course] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Ivanova_AS41_course] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Ivanova_AS41_course] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Ivanova_AS41_course] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Ivanova_AS41_course] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Ivanova_AS41_course] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Ivanova_AS41_course] SET  READ_WRITE 
GO


